package middleware

import (
	"strings"

	"likeadmin/backend/internal/gencrud"
)

// actionNotes maps controller/action to the first Unicode word of PHP @notes.
// PHP OperationLog uses preg_match('/\s(\w+)/u', $doc) and stores $values[0]
// (the full match, including the leading whitespace).
var actionNotes = map[string]string{
	"login/account":    "账号登录",
	"login/logout":     "退出登录",
	"workbench/index":  "工作台",
	"config/getconfig": "基础配置",
	"config/dict":      "根据类型获取字典数据",

	"auth.admin/lists":       "查看管理员列表",
	"auth.admin/add":         "添加管理员",
	"auth.admin/edit":        "编辑管理员",
	"auth.admin/delete":      "删除管理员",
	"auth.admin/detail":      "查看管理员详情",
	"auth.admin/myself":      "获取当前管理员信息",
	"auth.admin/editself":    "编辑超级管理员信息",
	"auth.admin/all":         "获取管理员数据",
	"auth.menu/route":        "获取菜单路由",
	"auth.menu/lists":        "获取菜单列表",
	"auth.menu/detail":       "菜单详情",
	"auth.menu/add":          "添加菜单",
	"auth.menu/edit":         "编辑菜单",
	"auth.menu/delete":       "删除菜单",
	"auth.menu/updatestatus": "更新状态",
	"auth.menu/all":          "获取菜单数据",
	"auth.role/lists":        "查看角色列表",
	"auth.role/add":          "添加权限",
	"auth.role/edit":         "编辑角色",
	"auth.role/delete":       "删除角色",
	"auth.role/detail":       "查看角色详情",
	"auth.role/all":          "获取角色数据",

	"dept.dept/lists":      "部门列表",
	"dept.dept/leaderdept": "上级部门",
	"dept.dept/add":        "添加部门",
	"dept.dept/edit":       "编辑部门",
	"dept.dept/delete":     "删除部门",
	"dept.dept/detail":     "获取部门详情",
	"dept.dept/all":        "获取部门数据",
	"dept.jobs/lists":      "岗位列表",
	"dept.jobs/add":        "添加岗位",
	"dept.jobs/edit":       "编辑岗位",
	"dept.jobs/delete":     "删除岗位",
	"dept.jobs/detail":     "获取岗位详情",
	"dept.jobs/all":        "获取岗位数据",

	"file/lists":      "文件列表",
	"file/move":       "文件移动成功",
	"file/rename":     "重命名文件",
	"file/delete":     "删除文件",
	"file/listcate":   "分类列表",
	"file/addcate":    "添加文件分类",
	"file/editcate":   "编辑文件分类",
	"file/delcate":    "删除文件分类",
	"upload/image":    "上传图片",
	"upload/video":    "上传视频",
	"upload/file":     "上传文件",
	"download/export": "导出文件",

	"tenant.tenant/lists":        "用户列表",
	"tenant.tenant/detail":       "获取用户详情",
	"tenant.tenant/add":          "新增租户信息",
	"tenant.tenant/edit":         "编辑用户信息",
	"tenant.tenant/delete":       "删除租户",
	"tenant.tenant_admin/lists":  "获取租户管理员账号",
	"tenant.tenant_admin/detail": "获取租户管理员账号",
	"tenant.tenant_admin/add":    "创建租户管理员账号",
	"tenant.tenant_admin/edit":   "编辑租户管理员账号",
	"tenant.tenant_admin/delete": "删除租户管理员账号",
	"tenant.tenantadmin/lists":   "获取租户管理员账号",
	"tenant.tenantadmin/detail":  "获取租户管理员账号",
	"tenant.tenantadmin/add":     "创建租户管理员账号",
	"tenant.tenantadmin/edit":    "编辑租户管理员账号",
	"tenant.tenantadmin/delete":  "删除租户管理员账号",
	"tenant.tenant_user/lists":   "获取租户用户列表",
	"tenant.tenant_user/detail":  "获取租户用户详情",
	"tenant.tenantuser/lists":    "获取租户用户列表",
	"tenant.tenantuser/detail":   "获取租户用户详情",

	"setting.web.web_setting/getwebsite":        "获取网站信息",
	"setting.web.web_setting/setwebsite":        "设置网站信息",
	"setting.web.web_setting/getcopyright":      "获取备案信息",
	"setting.web.web_setting/setcopyright":      "设置备案信息",
	"setting.web.web_setting/getagreement":      "获取政策协议",
	"setting.web.web_setting/setagreement":      "设置政策协议",
	"setting.web.web_setting/getsitestatistics": "获取站点统计配置",
	"setting.web.web_setting/setsitestatistics": "获取站点统计配置",
	"setting.pay.pay_config/lists":              "获取支付配置列表",
	"setting.user.user/getconfig":               "获取用户设置",
	"setting.user.user/setconfig":               "设置用户设置",
	"setting.user.user/getregisterconfig":       "获取注册配置",
	"setting.user.user/setregisterconfig":       "设置注册配置",
	"setting.transaction_settings/getconfig":    "获取交易设置",
	"setting.transaction_settings/setconfig":    "设置交易设置",
	"setting.customer_service/getconfig":        "获取客服设置",
	"setting.customer_service/setconfig":        "设置客服设置",
	"setting.system.cache/clear":                "清除系统缓存",
	"setting.system.system/info":                "获取系统环境信息",
	"setting.system.log/lists":                  "查看系统日志列表",
	"setting.dict.dict_type/lists":              "获取字典类型列表",
	"setting.dict.dict_type/add":                "添加字典类型",
	"setting.dict.dict_type/edit":               "编辑字典类型",
	"setting.dict.dict_type/delete":             "删除字典类型",
	"setting.dict.dict_type/detail":             "获取字典详情",
	"setting.dict.dict_type/all":                "获取字典类型数据",
	"setting.dict.dict_data/lists":              "获取字典数据列表",
	"setting.dict.dict_data/add":                "添加字典数据",
	"setting.dict.dict_data/edit":               "编辑字典数据",
	"setting.dict.dict_data/delete":             "删除字典数据",
	"setting.dict.dict_data/detail":             "获取字典详情",
	"setting.storage/lists":                     "获取存储引擎列表",
	"setting.storage/detail":                    "存储配置信息",
	"setting.storage/setup":                     "设置存储参数",
	"setting.storage/change":                    "切换存储引擎",
	"setting.pay.pay_config/setconfig":          "设置支付配置",
	"setting.pay.pay_config/getconfig":          "获取支付配置",
	"setting.pay.pay_way/getpayway":             "获取支付方式",
	"setting.pay.pay_way/setpayway":             "设置支付方式",

	"notice.notice/settinglists":  "查看通知设置列表",
	"notice.notice/detail":        "查看通知设置详情",
	"notice.notice/set":           "通知设置",
	"notice.sms_config/getconfig": "获取短信配置",
	"notice.sms_config/setconfig": "短信配置",
	"notice.sms_config/detail":    "查看短信配置详情",
	"notice.smsconfig/getconfig":  "获取短信配置",
	"notice.smsconfig/setconfig":  "短信配置",
	"notice.smsconfig/detail":     "查看短信配置详情",

	"crontab.crontab/lists":      "定时任务列表",
	"crontab.crontab/add":        "添加定时任务",
	"crontab.crontab/detail":     "查看定时任务详情",
	"crontab.crontab/edit":       "编辑定时任务",
	"crontab.crontab/delete":     "删除定时任务",
	"crontab.crontab/operate":    "操作定时任务",
	"crontab.crontab/expression": "获取规则执行时间",

	"tools.generator/datatable":     "获取数据库中所有数据表信息",
	"tools.generator/generatetable": "获取已选择的数据表",
	"tools.generator/selecttable":   "选择数据表",
	"tools.generator/generate":      "生成代码",
	"tools.generator/download":      "下载文件",
	"tools.generator/preview":       "预览代码",
	"tools.generator/synccolumn":    "同步字段",
	"tools.generator/edit":          "编辑表信息",
	"tools.generator/detail":        "获取已选择的数据表详情",
	"tools.generator/delete":        "删除已选择的数据表信息",
	"tools.generator/getmodels":     "获取模型",

	"upgrade.upgrade/lists":       "查看系统更新列表",
	"upgrade.upgrade/upgrade":     "执行系统更新",
	"upgrade.upgrade/downloadpkg": "下载更新包",

	"article.article/lists":             "查看资讯列表",
	"article.article/add":               "添加资讯",
	"article.article/edit":              "编辑资讯",
	"article.article/delete":            "删除资讯",
	"article.article/detail":            "资讯详情",
	"article.article/updatestatus":      "更改资讯状态",
	"article.article_cate/lists":        "查看资讯分类列表",
	"article.article_cate/add":          "添加资讯分类",
	"article.article_cate/edit":         "编辑资讯分类",
	"article.article_cate/delete":       "删除资讯分类",
	"article.article_cate/detail":       "资讯分类详情",
	"article.article_cate/updatestatus": "更改资讯分类状态",
	"article.article_cate/all":          "获取文章分类",

	"user.user/lists":           "用户列表",
	"user.user/detail":          "获取用户详情",
	"user.user/edit":            "编辑用户信息",
	"user.user/adjustusermoney": "调整用户余额",
	"user.user/adjustmoney":     "调整用户余额",

	"recharge.recharge/getconfig":   "获取充值设置",
	"recharge.recharge/setconfig":   "充值设置",
	"recharge.recharge/lists":       "充值记录",
	"recharge.recharge/refund":      "退款",
	"recharge.recharge/refundagain": "重新退款",

	"finance.refund/stat":                 "退还统计",
	"finance.refund/record":               "退款记录",
	"finance.refund/log":                  "退款日志",
	"finance.account_log/lists":           "账户流水明细",
	"finance.account_log/getumchangetype": "用户余额变动类型",

	"decorate.page/detail":   "获取装修修页面详情",
	"decorate.page/save":     "保存装修配置",
	"decorate.tabbar/detail": "底部导航详情",
	"decorate.tabbar/save":   "底部导航保存",
	"decorate.data/article":  "文章列表",
	"decorate.data/pc":       "pc设置",

	"channel.official_account_setting/getconfig":   "获取公众号配置",
	"channel.official_account_setting/setconfig":   "设置公众号配置",
	"channel.official_account_menu/save":           "保存菜单",
	"channel.official_account_menu/publish":        "保存发布菜单",
	"channel.official_account_menu/saveandpublish": "保存发布菜单",
	"channel.official_account_menu/detail":         "查看菜单详情",
	"channel.official_account_reply/lists":         "查看回复列表",
	"channel.official_account_reply/add":           "添加回复",
	"channel.official_account_reply/detail":        "查看回复详情",
	"channel.official_account_reply/edit":          "编辑回复",
	"channel.official_account_reply/delete":        "删除回复",
	"channel.official_account_reply/sort":          "更新排序",
	"channel.official_account_reply/status":        "更新状态",
	"channel.official_account_reply/index":         "微信公众号回调",
	"channel.mnp_settings/getconfig":               "获取小程序配置",
	"channel.mnp_settings/setconfig":               "设置小程序配置",
	"channel.open_setting/getconfig":               "获取微信开放平台设置",
	"channel.open_setting/setconfig":               "微信开放平台设置",
	"channel.web_page_setting/getconfig":           "获取H5设置",
	"channel.web_page_setting/setconfig":           "H5设置",
	"channel.app_setting/getconfig":                "获取App设置",
	"channel.app_setting/setconfig":                "App设置",

	"setting.hot_search/getconfig": "获取热门搜索",
	"setting.hot_search/setconfig": "设置热门搜索",
}

// ActionNotes returns the PHP-equivalent operation name (leading space + first @notes word).
func ActionNotes(controller, action string) string {
	key := strings.ToLower(strings.TrimSpace(controller) + "/" + strings.TrimSpace(action))
	if n, ok := actionNotes[key]; ok {
		return " " + n
	}
	compact := strings.ReplaceAll(key, "_", "")
	for k, n := range actionNotes {
		if strings.ReplaceAll(k, "_", "") == compact {
			return " " + n
		}
	}
	if n := gencrud.PHPActionNotes(controller, action); n != "" {
		return " " + n
	}
	return "无法获取操作名称，请给控制器方法注释"
}
