package cron

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func runVendorPublish(args []string) string {
	force := false
	for _, a := range args {
		if a == "--force" || a == "-f" {
			force = true
		}
	}
	root := runtimeRoot()
	if root == "" {
		return ""
	}
	installed := filepath.Join(root, "vendor", "composer", "installed.json")
	packages, err := readComposerPackages(installed)
	if err != nil || len(packages) == 0 {
		return ""
	}
	configDir := filepath.Join(root, "config")
	_ = os.MkdirAll(configDir, 0755)
	for _, pkg := range packages {
		think, _ := pkg["extra"].(map[string]any)
		if think == nil {
			continue
		}
		extra, _ := think["think"].(map[string]any)
		if extra == nil {
			continue
		}
		cfg := extra["config"]
		if cfg == nil {
			continue
		}
		name := fmt.Sprint(pkg["name"])
		installPath := filepath.Join(root, "vendor", name)
		for cfgName, file := range thinkConfigFiles(cfg) {
			target := filepath.Join(configDir, cfgName+".php")
			source := filepath.Join(installPath, file)
			if st, err := os.Stat(target); err == nil && !st.IsDir() && !force {
				fmt.Println("File " + target + " exist!")
				continue
			}
			if _, err := os.Stat(source); err != nil {
				fmt.Println("File " + source + " not exist!")
				continue
			}
			body, err := os.ReadFile(source)
			if err != nil {
				fmt.Println("File " + source + " not exist!")
				continue
			}
			if err := os.WriteFile(target, body, 0644); err != nil {
				return err.Error()
			}
		}
	}
	fmt.Println("Succeed!")
	return ""
}

func thinkConfigFiles(cfg any) map[string]string {
	out := map[string]string{}
	switch v := cfg.(type) {
	case map[string]any:
		for k, file := range v {
			out[k] = fmt.Sprint(file)
		}
	case []any:
		for i, file := range v {
			out[fmt.Sprint(i)] = fmt.Sprint(file)
		}
	}
	return out
}

func runServiceDiscover(args []string) string {
	root := runtimeRoot()
	if root == "" {
		return ""
	}
	installed := filepath.Join(root, "vendor", "composer", "installed.json")
	packages, err := readComposerPackages(installed)
	if err != nil {
		return ""
	}
	var services []string
	for _, pkg := range packages {
		think, _ := pkg["extra"].(map[string]any)
		if think == nil {
			continue
		}
		extra, _ := think["think"].(map[string]any)
		if extra == nil {
			continue
		}
		switch v := extra["services"].(type) {
		case []any:
			for _, s := range v {
				if t := fmt.Sprint(s); t != "" && t != "<nil>" {
					services = append(services, t)
				}
			}
		case string:
			if v != "" {
				services = append(services, v)
			}
		}
	}
	header := "// This file is automatically generated at:" + time.Now().Format("2006-01-02 15:04:05") + "\ndeclare (strict_types = 1);\n"
	content := "<?php \n" + header + "return " + phpVarExportStrings(services) + ";"
	if err := os.MkdirAll(filepath.Join(root, "vendor"), 0755); err != nil {
		return err.Error()
	}
	if err := os.WriteFile(filepath.Join(root, "vendor", "services.php"), []byte(content), 0644); err != nil {
		return err.Error()
	}
	fmt.Println("Succeed!")
	return ""
}

func readComposerPackages(path string) ([]map[string]any, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var raw any
	if err := json.Unmarshal(b, &raw); err != nil {
		return nil, err
	}
	var list []any
	switch v := raw.(type) {
	case map[string]any:
		if pkgs, ok := v["packages"].([]any); ok {
			list = pkgs
		}
	case []any:
		list = v
	}
	out := make([]map[string]any, 0, len(list))
	for _, item := range list {
		if m, ok := item.(map[string]any); ok {
			out = append(out, m)
		}
	}
	return out, nil
}

func phpVarExportStrings(items []string) string {
	var b strings.Builder
	b.WriteString("array (\n")
	for i, s := range items {
		esc := strings.ReplaceAll(s, `\`, `\\`)
		esc = strings.ReplaceAll(esc, `'`, `\'`)
		fmt.Fprintf(&b, "  %d => '%s',\n", i, esc)
	}
	b.WriteString(")")
	return b.String()
}
