package generator

import (
	"strings"
	"time"

	"likeadmin/backend/internal/model"
)

// BuildGo produces Go runtime metadata for generate_type=1.
// It is NOT part of Preview()/Build() so PHP zip pairing stays 9 files.
func BuildGo(t model.GenerateTable, cols []model.GenerateColumn) []File {
	return BuildGoAt(t, cols, time.Now())
}

func BuildGoAt(t model.GenerateTable, cols []model.GenerateColumn, now time.Time) []File {
	c := newCtx(t, cols, now)
	return []File{c.genGoRuntime()}
}

func (c *ctx) genGoRuntime() File {
	ident := goIdent(c.module + "_" + c.tableName)
	route := c.vueRoute()
	app := goModuleApp(c.module)
	content := `// Code generated by likeadmin generator. DO NOT EDIT.
// Served at runtime by internal/gencrud (no PHP module is written).
package generated

const (
	Table` + ident + ` = "` + c.table + `"
	Route` + ident + ` = "` + route + `"
	App` + ident + `   = "` + app + `"
)
`
	return File{
		Name:    strings.ToLower(c.module+"_"+c.tableName) + ".go",
		Type:    "go",
		Content: content,
		RelPath: "go/" + strings.ToLower(c.module+"_"+c.tableName) + ".go",
	}
}

func goModuleApp(module string) string {
	switch strings.ToLower(strings.TrimSpace(module)) {
	case "", "platform", "platformapi", "admin":
		return "platformapi"
	case "tenant", "tenantapi":
		return "tenantapi"
	case "api", "index", "user":
		return "api"
	default:
		return strings.ToLower(strings.TrimSpace(module))
	}
}

func goIdent(s string) string {
	return Studly(s)
}
